### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by vtfarah** [eduardoklosowski/deduplicated#1]
Eduardo, Sou péssimo em Pyton e rodo Windows... posso usar o app? poderia ajudar em como rodar? Grato

**Comment by eduardoklosowski** [comment]
Teoricamente funciona, tomei esse cuidado na hora de escrever o código, porém não cheguei a testar.

Único ponto é a interface web, por usar Flask que tem dependências compiladas e não sei como funciona exatamente no Windows, mas se conseguir instalar o Flask deve funcionar corretamente. A opção por linha de comando não tem essa dependência e funciona sem o Flask.

**Comment by eduardoklosowski** [comment]
Consegui fazer alguns testes no Windows e funcionou, porém tem alguns detalhes que devem ser observados:

Primeiro se for utilizar o git, ele tem quem que estar no PATH do sistema, pode instalá-lo pelo link https://msysgit.github.io/ e no final colocar o diretório C:\Program Files (x86)\Git\bin no PATH dentro das variáveis de ambiente nas propriedades do sistema. Mesmo procedimento que alguns faziam com o Java.

Fiz a instalação com o pip conforme descrito no meu blog (https://eduardoklosowski.wordpress.com/2015/03/17/remover-arquivos-duplicados/) e por isso precisei do git. Para instalar sem o git, a partir do código fonte execute o comando python setup.py install.

Se durante a instalação do Python foi marcado para adicionar no PATH do sistema você pode executar os comandos diretamente, caso contrário tem que passar o caminho completo, como C:\Python34\Scripts\deduplicated.exe check C:\Users\eduardo em vez de deduplicated check C:\Users\eduardo.

Com relação a interface web ainda tem o problema referente a instalação das dependências compiladas, se futuramente eu descobrir como funciona aviso.

Resumo:
Linha de comando: 100%, só que precisa tomar mais cuidado com alguns detalhes do ambiente.
Interface web: não cheguei a testar, mas deve funcionar se conseguir instalar o Flask e o Gunicorn.

**Comment by eduardoklosowski** [comment]
Consegui fazer os testes e a interface web funcionou no Windows, primeiro é necessário instalar o MarkupSafe que é compilado, no caso usei o arquivo disponível em http://www.lfd.uci.edu/~gohlke/pythonlibs/#markupsafe, uma vez baixado para a versão do python instalado, basta um pip install arquivo.whl. Depois só seguir a instalação normalmente.

Em relação ao gunicorn, instalou porém não levantou o serviço, mas como ele não é 100% obrigatório vou tirar essa dependência para usar o servidor do Flask, deixando compatível. Porém quem quiser melhor desempenhou ou segurança pode subir o gunicorn ou outro servidor wsgi por fora do código.
